import React from "react";
import Router from "next/router";
import Head from "next/head";
import { Auth } from "@polybase/auth";

export default function Login() {
  const [email, setEmail] = React.useState("");
  const [password, setPassword] = React.useState("");
  const auth = typeof window !== "undefined" ? new Auth() : null;

  const handleLogin = async (e) => {
    e.preventDefault();
    const authState = await auth.signIn();
    console.log(authState);
    console.log(email, password);
    Router.push("/home");
  };
  // TODO: Integrate Arcana Login
  return (
    <>
      <Head>
        <title>FreeLance </title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="relative flex flex-col justify-center min-h-screen overflow-hidden">
        <div className="w-full p-6 m-auto bg-[#1a1e27] text-white rounded-md shadow-md lg:max-w-xl">
          <h1 className="text-3xl font-semibold text-center text-[#0284c7]">
            Sign in
          </h1>
          <form className="mt-6" onSubmit={handleLogin}>
            <div className="mt-6">
              <button className="w-full bg-[#0284c7] text-white text-lg px-5 py-2 rounded-xl">
                Login
              </button>
            </div>
          </form>
        </div>
      </div>
    </>
  );
}
